on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: crmaricle.azurecr.io
        username: ${{ secrets.acr_crmaricle_username }}
        password: ${{ secrets.acr_crmaricle_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/chores.API" -f  "chores.API/Dockerfile" -t crmaricle.azurecr.io/choresapp:${{ github.sha }}
        docker push crmaricle.azurecr.io/choresapp:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_choresapp_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep choresapp7c75 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace choresapp7c75`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: choresapp7c75
        container-registry-url: crmaricle.azurecr.io
        container-registry-username: ${{ secrets.acr_crmaricle_username }}
        container-registry-password: ${{ secrets.acr_crmaricle_password }}
        secret-name: choresappdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: choresapp7c75
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          crmaricle.azurecr.io/choresapp:${{ github.sha }}
        imagepullsecrets: |
          choresappdockerauth